name: C++ Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # --- Install dependencies ---
      - name: Install tool-chain & deps
        run: |
          sudo apt-get update
          # add llvm snapshot repo
          wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key \
            | sudo tee /usr/share/keyrings/llvm-snapshot.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg] \
               http://apt.llvm.org/$(lsb_release -sc)/ \
               llvm-toolchain-$(lsb_release -sc)-18 main" \
            | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang-18 clang++-18 ninja-build \
            libvulkan-dev libglfw3-dev libglm-dev

      # --- Configure (generate compile_commands.json) ---
      - name: Configure with CMake
        run: |
          cmake -B build -S . -G Ninja \
                -DCMAKE_C_COMPILER=clang-18 \
                -DCMAKE_CXX_COMPILER=clang++-18 \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      # --- Run clang-format / clang-tidy ---
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          compile-commands: build/compile_commands.json
          thread-comments: update

      - name: Fail on remaining errors
        if: ${{ steps.linter.outputs.errors != '0' }}
        run: exit 1
