name: C++ Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # --- Install dependencies ---
      - name: Install system Vulkan headers
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libvulkan-dev

      # --- Configure (generate compile_commands.json) ---
      - name: Configure with CMake
        run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      # --- Run clang-format / clang-tidy ---
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          compile-commands: build/compile_commands.json
          thread-comments: update

      - name: Fail on remaining errors
        if: ${{ steps.linter.outputs.errors != '0' }}
        run: exit 1
